/home/zhanghong/anaconda3/bin/python3 main.py --data-root /ssd3/zhangh/dataset/cifar10/ \
--save /ssd3/zhangh/results/debug \
--data cifar10 \
--gpu 4 \
--arch msdnet \
--batch-size 64 \
--epochs 300 \
--nBlocks 10 \
--stepmode even \
--step 2 \
--base 4 \
--nChannels 16 \
-j 16
